server:
  port: 8070

spring:
  application:
    name: consumer
  devtools:
    restart:
      enabled: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8080/eureka
#    fetch-registry: true
#    register-with-eureka: true

feign:
  hystrix:
    enabled: true
