server:
  port: 8071

spring:
  application:
    name: provider
  devtools:
    restart:
      enabled: true
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: MZBANK
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8080/eureka


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: CloudProvider.entity
  mapper-locations: classpath:/mapper/*.xml

